PWGHF: Add OmegaC0 workflows that use KFParticle (#6327)
* add OmegaC0 table and kf table

* add Tasks of  reconstructing OmegaC0 with the KFParticle

* add header file for OmegaC0 ML\

* Please consider the following formatting changes

* Update CMakeLists.txt

* Update HfMlResponseOmegaCToOmegaPi.h

* Update candidateCreatorOmegacToOmegaPiWithKFP.cxx

* Update treeCreatorOmegacToOmegaPiWithKFP.cxx

* Please consider the following formatting changes

* Update CMakeLists.txt

* Update and rename HfMlResponseOmegaCToOmegaPi.h to HfMlResponseOmegacToOmegaPi.h

complete the documentation and change the file name.

* Update candidateSelectorOmegacToOmegaPiWithKFP.cxx

complete the documentation, remove useless lines, and use the "registry"

* Update HfMlResponseOmegacToOmegaPi.h

* Update PWGHF/DataModel/CandidateReconstructionTables.h

Co-authored-by: Vít Kučera <vit.kucera@cern.ch>

* Update PWGHF/TableProducer/treeCreatorOmegacToOmegaPiWithKFP.cxx

Co-authored-by: Vít Kučera <vit.kucera@cern.ch>

* change CMakeLists.txt as requested.

respect alphabetic ordering as requested.

* change to use existing columns

* Please consider the following formatting changes

* Update candidateCreatorOmegacToOmegaPiWithKFP.cxx

fill the documentation.

* fixing some errors

* Update CandidateReconstructionTables.h

* Update CandidateReconstructionTables.h

* Update CandidateReconstructionTables.h

* changing some things as comment reqeust and fixing bugs

* Delete unused tables

* Please consider the following formatting changes

* Update candidateCreatorOmegacToOmegaPiWithKFP.cxx

using "static_cast<int>(..)" instead of "int(..)"

* Update candidateCreatorOmegacToOmegaPiWithKFP.cxx

* Please consider the following formatting changes

* using exist table instead of duplication one

* using exist table

* deleting the DCAfitter

* deleting the DCAfitter, unused header and fixing

* Please consider the following formatting changes

* Update candidateCreatorOmegacToOmegaPiWithKFP.cxx

* Update treeCreatorOmegacToOmegaPiWithKFP.cxx

* adding KFParticle for omegac in existing omegac0 to omega pi workflow(candidateCreatorXic0Omegac0, treeCreatorOmegacToOmegaPi.cxx)

* adding KFParticle table for Omegac0 to Omega Pi and deleting duplication table added before

* Delete PWGHF/TableProducer/treeCreatorOmegacToOmegaPiWithKFP.cxx

now use existing workflow instead of  duplication.

* Delete PWGHF/TableProducer/candidateSelectorOmegacToOmegaPiWithKFP.cxx

now use existing workflow instead of  duplication.

* Delete PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx

now use existing workflow instead of duplication.

* Delete PWGHF/TableProducer/candidateCreatorOmegacToOmegaPiWithKFP.cxx

now use existing workflow instead of  duplication.

* Revert "Delete PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx"

This reverts commit 8ac8b28f7015e542e88d555372f3d0154aae1934.

* Please consider the following formatting changes

* Update candidateCreatorXic0Omegac0.cxx

* Update CandidateSelectionTables.h

* Please consider the following formatting changes

* Update CandidateSelectionTables.h

* Update PWGHF/Core/HfMlResponseOmegacToOmegaPi.h

Co-authored-by: Fabrizio <fabrizio.grosa@cern.ch>

* Update PWGHF/Core/HfMlResponseOmegacToOmegaPi.h

Co-authored-by: Fabrizio <fabrizio.grosa@cern.ch>

* Update PWGHF/Core/HfMlResponseOmegacToOmegaPi.h

Co-authored-by: Fabrizio <fabrizio.grosa@cern.ch>

* deleting duplication table

* Delete PWGHF/Core/HfMlResponseOmegacToOmegaPi.h

* Update candidateCreatorXic0Omegac0.cxx

fixing bug: Incorrectly filling a variable into a table twice

* Update candidateCreatorXic0Omegac0.cxx

* Please consider the following formatting changes

* Update candidateCreatorXic0Omegac0.cxx

fixing errors

* Update candidateCreatorXic0Omegac0.cxx

keep all the cospa in the non-KF tables are referred to the PV.

* Update CandidateReconstructionTables.h

* Please consider the following formatting changes

* Update treeCreatorOmegacToOmegaPi.cxx

* no longer filling nSigma into KF-table in candidateCreator

* Update candidateCreatorXic0Omegac0.cxx

deleting unused variables

* Update candidateCreatorXic0Omegac0.cxx

deleting unused variables

* Update treeCreatorOmegacToOmegaPi.cxx

fixing bugs

* Update treeCreatorOmegacToOmegaPi.cxx

* Update candidateCreatorXic0Omegac0.cxx

* Update candidateCreatorXic0Omegac0.cxx

* Update treeCreatorOmegacToOmegaPi.cxx

* Update candidateCreatorXic0Omegac0.cxx

fixing the errors: 
 error: 'SetField' is not a member of 'KFParticle'
 error: unused parameter 'bcWithTimeStamps' [-Werror=unused-parameter]

* Update candidateCreatorXic0Omegac0.cxx

---------

Co-authored-by: root <root@USER-20161104VR.localdomain>
Co-authored-by: ALICE Action Bot <alibuild@cern.ch>
Co-authored-by: Vít Kučera <vit.kucera@cern.ch>
Co-authored-by: Fabrizio <fabrizio.grosa@cern.ch>